default_platform(:ios)

platform :ios do

  # -----------------------
  # Development / Firebase
  # -----------------------
  desc "CI: Build Development IPA and upload to Firebase App Distribution"
  lane :ci_dev do
    UI.user_error!("This lane is CI-only") unless ENV['CI']
    # Debug: list certificates & profiles
    sh "security find-identity -v -p codesigning"
    sh "ls -la ~/Library/MobileDevice/Provisioning\\ Profiles"

    build_app(
      project: "MockWorkoutApp/MockWorkoutApp.xcodeproj",
      scheme: "MockWorkoutApp copy",
      export_method: "ad-hoc",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "huynang.Demo.dev" => "demo ad hoc dev"
        }
      },
      clean: true
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_IOS_APP_ID"],
      testers: ENV["FIREBASE_TESTERS"],
      release_notes: "CI Development build via GitHub Actions"
    )
  end

end   
